repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
      - id: rst-linter
        name: Check rST
        files: (README\.rst)|(CHANGELOG\.rst)

  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        additional_dependencies:
          - toml

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.9.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
        args: [-l, '79', -t, py38]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.18.0
    hooks:
      - id: eslint
        additional_dependencies:
          # Manually mirror dev dependencies related to eslint here
          - babel-eslint@10.1.0
          - eslint@7.17.0
          - eslint-config-airbnb@18.2.1
          - eslint-config-prettier@6.15.0
          - eslint-config-wesbos@1.0.1
          - eslint-plugin-html@6.1.1
          - eslint-plugin-import@2.22.1
          - eslint-plugin-jsx-a11y@6.4.1
          - eslint-plugin-prettier@3.3.1
          - eslint-plugin-react@7.22.0
          - eslint-plugin-react-hooks@4.2.0
          - prettier@2.1.2
          - react@16.12.0

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        files: \.(css|less|scss|graphql|gql|html|json|mdx|yaml|yml)$
