apiVersion: v1
kind: Secret
metadata:
  name: jwt-authorizer-config
type: Opaque
stringData:
  authorizer.yaml: |
    global:
      REALM: lsst.org
    
      # Options are Bearer, Basic, none
      WWW_AUTHENTICATE: Basic
      LOGLEVEL: DEBUG
    
      # Authorizer Configurations
      # NO_AUTHORIZE: True
    
      # Resource Checkers
      RESOURCE_CHECKS_DEFAULT: 
        - group_membership
    
      # group_membership options
      GROUP_MAPPING:
        exec:user: lsst_int_lspdev
        read:workspace: lsst_int_lspdev
        read:workspace/user: lsst_int_lspdev
        write:workspace/user: lsst_int_lspdev
        exec:portal: lsst_int_lspdev
        exec:notebook: lsst_int_lspdev
        read:tap: lsst_int_lspdev
        read:image: lsst_int_lspdev
    
    
      OAUTH2_JWT:
        ISS: https://{{ HOSTNAME }}
        KEY_ID: reissuer
        AUD:
          DEFAULT: https://{{ HOSTNAME }}
          INTERNAL: https://{{ HOSTNAME }}/api
        KEY: |
{{ ISSUER_PRIVATE_KEY_INDENT_10 }}
    
      SECRET_KEY: {{ AUTHORIZER_FLASK_SECRET }}
    
      OAUTH2_STORE_SESSION:
        TICKET_PREFIX: oauth2_proxy
        REDIS_URL: redis://redis-service.{{ NAMESPACE }}.svc.cluster.local:6379/0
        OAUTH2_PROXY_SECRET: {{ OAUTH2_PROXY_COOKIE_SECRET }}
    
      KNOWN_CAPABILITIES:
        exec:portal: Use the Portal to execute operations. Mostly used from notebook APIs.
        read:image: Read images from the SODA and other image retrieval interfaces
        read:image/metadata: Read image metadata from SIA and other image interfaces
        read:tap: Execute SELECT queries in the TAP interface on project datasets
        read:tap/efd: Execute SELECT queries in the TAP interface on EFD datasets
        read:tap/user: Execute SELECT queries in the TAP interface on your data
        write:tap/user: Upload tables to your database workspace
        read:tap/history: Read the history of your TAP queries.
        read:workspace: Read project datasets from the file workspace
        read:workspace/user: Read the data in your file workspace
        write:workspace/user: Write data to your file workspace
    
      # lsst_group_membership options
      # GROUP_DEPLOYMENT_PREFIX: lsst_int_lsp_int_
      ISSUERS:
        https://cilogon.org:
          audience: {{ OAUTH2_PROXY_CLIENT_ID }}
          issuer_key_ids: ["244B235F6B28E34108D101EAC7362C4E"]
        https://{{ HOSTNAME }}:
          audience: ["https://{{ HOSTNAME }}", "https://{{ HOSTNAME }}/api"]
          issuer_key_ids: ["reissuer"]

