apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
  name: well-known-jwks
spec:
  rules:
  - host: {{ HOSTNAME }}
    http:
      paths:
      - backend:
          serviceName: well-known-jwks
          servicePort: 80
        path: /.well-known/jwks.json
